config/routes.rb
Rails.application.routes.draw do
  namespace :everybodys do
    resources :tweets, only: %i[index]
    resources :categories, only: %i[index show]
    resources :users, only: %i[index show]
  end
  root 'home#top'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'users/tweet_fetch', to: 'users#tweet_fetch'
  resources :users, only: %i[edit show update destroy]
  resources :tweets, only: %i[index update edit]
  resources :categories, except: [:show]
  resources :post_users, only: %i[index show]
  patch 'tweets/:id/clip', to: 'tweets#toggle_status', as: 'toggle_status'
  patch 'categories/category_publish/:id', to: 'categories#category_publish', as: 'category_publish'
  get 'tweets/hashtag', to: 'tweets#hashtag'
end

app/controllers/everybodys/base.rb
class Everybodys::Base < ApplicationController
  layout 'layouts/everybodys/everybodys'
  before_action :login_required
end

app/controllers/everybodys/categories_controller.rb
class Everybodys::CategoriesController < Everybodys::Base
  before_action :set_category, only: [:show]

  def index
    @categories = Category.where(status: :publish).group(:name).having('count(*) >= 1')
  end

  def show
    # 任意のカテゴリーに紐づけられたツイート一覧を表示する
    # 別のユーザが同じ名前のカテゴリー名を作成している場合、同じ名前でツイートをまとめる
    if params[:user].present?
      tweets = User.find(params[:user]).categories.find(params[:id]).tweets
    else
      tweets = Category.merge_same_category_tweet(@category.name)
    end

    @tweets = tweets.page(params[:page]).per(30)
    render template: 'everybodys/tweets/index'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/everybodys/tweets_controller.rb
class Everybodys::TweetsController < Everybodys::Base
  def index
    # カテゴリー付きで公開ツイートのみを抽出
    # 公開/非公開設定はカテゴリーごとに設定してある
    @tweets = Tweet.joins(:categories).where(categories: { status: :publish }).distinct.page(params[:page]).per(30)
    render template: 'everybodys/tweets/index'
  end
end

app/controllers/everybodys/users_controller.rb
class Everybodys::UsersController < Everybodys::Base
  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  def show
    @categories = @user.categories.where(status: :publish)
    render template: 'everybodys/categories/index', user: @user
  end

  private
   def set_user
     @user = User.find(params[:id])
   end
end

app/helpers/everybodys/tweets_helper.rb
module Everybodys::TweetsHelper
end

app/views/layouts/everybodys/_sidenav.html.erb
<ul id="slide-out" class="sidenav sidenav-fixed">
  <li>
    <%= link_to tweets_path do%>
      自分のお気に入りを見る<i class="material-icons">person</i>
    <% end %>
  </li>
  <li><div class="divider"></div></li>
  <li><%= link_to "カテゴリー一覧", everybodys_categories_path %></li>
  <li><%= link_to "ユーザ一覧", everybodys_users_path %></li>
</ul>

app/views/layouts/everybodys/everybodys.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Favdivider</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/header' %>
<%= render 'layouts/everybodys/sidenav' %>
<main>
  <div class="row">
    <%= yield %>
  </div>
</main>
</body>
</html>