config/routes.rb
Rails.application.routes.draw do
  namespace :everybodys do
    resources :tweets, only: %i[index]
    resources :categories, only: %i[index show]
    resources :users, only: %i[index show]
  end
  root 'home#top'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'users/tweet_fetch', to: 'users#tweet_fetch'
  resources :users, only: %i[edit show update destroy]
  resources :tweets, only: %i[index update edit]
  resources :categories, except: [:show]
  resources :post_users, only: %i[index show]
  patch 'tweets/:id/clip', to: 'tweets#toggle_status', as: 'toggle_status'
  patch 'categories/category_publish/:id', to: 'categories#category_publish', as: 'category_publish'
  get 'tweets/hashtag', to: 'tweets#hashtag'
end

app/models/tweet.rb
# frozen_string_literal: true

class Tweet < ApplicationRecord
  enum status: { default: 0, cliped: 1 }
  has_many :tweet_images, dependent: :destroy
  has_many :tweet_videos, dependent: :destroy
  has_many :relationships, dependent: :destroy
  accepts_nested_attributes_for :relationships, allow_destroy: true
  has_many :categories, through: :relationships, dependent: :destroy
  belongs_to :user
  belongs_to :post_user
  validates :user_id, :post_user_id, :status, presence: true
  validates :relationships, length: { maximum: 3 }

  default_scope -> { order(post_created_at: :DESC) }

  def self.fetch(user)
    client = Twitter::REST::Client.new do |config|
      config.consumer_key = ENV['APP_ID']
      config.consumer_secret = ENV['APP_SECRET']
      config.access_token = user.access_token
      config.access_token_secret = user.access_token_secret
    end

    # def collect_with_max_id(collection = [], max_id = nil, &block)
    #   response = yield(max_id)
    #   collection += response
    #   response.empty? ? collection.flatten : collect_with_max_id(collection, response.last.id - 1, &block)
    # end
    #
    # # いいね全件取得
    # def client.get_all_favorites(user)
    #   collect_with_max_id do |max_id|
    #     options = {count: 200, tweet_mode: "extended"}
    #     options[:max_id] = max_id unless max_id.nil?
    #     favorites(user, options)
    #   end
    # end

    tweets = client.favorites(user.uid.to_i, count: 200, tweet_mode: 'extended')
    Tweet.transaction do
      tweets.each do |tweet|
        next unless Tweet.new_tweet?(user.id, tweet.id)

        post_user = user.post_users.find_by(uid: tweet.user.id).presence
        if post_user # 投稿ユーザーがDBにすでにある場合
          _tweet = post_user.tweets.new(
            user_id: user.id,
            post_id: tweet.id,
            post_created_at: tweet.created_at,
            text: tweet.attrs[:full_text],
            favorite_count: tweet.favorite_count,
            is_quote_status: tweet.quoted_status?
          ).tap(&:save) # 一度セーブしてidを付与しバリデーションを通るようにする
        elsif post_user.nil? # 新規の投稿ユーザーの場合
          _tweet = user.post_users.new(
            uid: tweet.user.id,
            name: tweet.user.name,
            screen_name: tweet.user.screen_name,
            profile_description: tweet.user.description,
            profile_image: tweet.user.profile_image_url_https
          ).tap(&:save).tweets.new(
            user_id: user.id,
            post_id: tweet.id,
            post_created_at: tweet.created_at,
            text: tweet.attrs[:full_text],
            favorite_count: tweet.favorite_count,
            is_quote_status: tweet.quoted_status?
          ).tap(&:save)
        end
        if tweet.media?
          tweet.media.each do |media|
            if media.type == 'video'
              media.video_info.variants.each do |variant|
                if variant.content_type == 'video/mp4'
                  isBreak = true
                  _tweet.tweet_videos.new(tweet_video_url: variant.url,
                                          thumbnail: media.media_url_https)
                end
                break if isBreak
              end
            else
              _tweet.tweet_images.new(tweet_image_url: media.media_url_https)
            end
          end
        end
        _tweet.save!
      end
    end
  rescue StandardError
  end

  def self.search(user_id, queries = {})
    tweets = Tweet.where(user_id: user_id)
    return tweets if tweets.blank?

    if queries[:tweet_text].present?
      tweets = tweets.where('text LIKE ?', "%#{queries[:tweet_text]}%")
    end

    if queries[:like_num].present?
      tweets = tweets.where(favorite_count: queries[:like_num]..Float::INFINITY)
    end

    tweets = tweets.where(status: 1) if queries[:clip].present?

    if queries[:category_id].present?
      tweets = tweets.joins(:relationships).where(relationships: { category_id: queries[:category_id] })
    end

    tweets = tweets.reorder(favorite_count: 'DESC') if queries[:sort].present?

    tweets = tweets.where(is_quote_status: true) if queries[:quote].present?

    tweets = tweets.joins(:tweet_videos) if queries[:video].present?

    tweets = tweets.joins(:tweet_images).distinct if queries[:image].present?

    if queries[:reply].present?
      tweets = tweets.where('text LIKE ?', "@#{User.find(user_id).screen_name}%")
    end

    if queries[:hash_tag].present?
      tweets = tweets.where('text LIKE ?', "%#{queries[:hash_tag]}%")
    end

    tweets
  end

  def self.new_tweet?(user_id, tweet_id)
    Tweet.find_by(user_id: user_id, post_id: tweet_id).nil?
  end

  def toggle_clip!
    if default?
      cliped!
    else
      default!
    end
  end

  def self.hashtag_index(user)
    hashtags = user.tweets.where('text LIKE ?', '%#%').map do |tweet|
      tweet.text.scan(/#(\w+|(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+)/)
    end
    hashtags.flatten.group_by(&:downcase).map { |key, value| [key, value.count] }.to_h.sort_by { |_key, value| -value }.to_h
  end
end

app/controllers/everybodys/tweets_controller.rb
class Everybodys::TweetsController < Everybodys::Base
  def index
    # カテゴリー付きで公開ツイートのみを抽出
    # 公開/非公開設定はカテゴリーごとに設定してある
    @tweets = Tweet.joins(:categories).where(categories: { status: :publish }).distinct.page(params[:page]).per(30)
    render template: 'everybodys/tweets/index'
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :login_required
  before_action :set_tweet, only: %i[edit toggle_status]

  def index
    parameters = Parameter.new(params).define_params
    @tweets = Tweet.search(current_user.id, parameters).page(params[:page]).per(30)
  end

  def edit
    @categories = current_user.categories
    @category = Category.new
  end

  def update
    @relationship = Relationship.new(tweet_id: params[:id], category_id: params[:category_id])
    @category = Category.find(params[:category_id])
    respond_to do |format|
      if @relationship.save
        format.js {@status = 'success'}
      else
        format.js {@status = 'fail'}
      end
    end
  end

  def toggle_status
    @tweet.toggle_clip!
  end

  def hashtag
    @hashtags = Tweet.hashtag_index(current_user)
  end

  private
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
end

app/helpers/everybodys/tweets_helper.rb
module Everybodys::TweetsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<!-- Modal Structure -->
<div class="modal-content">
  <h4>Add Category</h4>
  <ul class="collapsible">
    <li>
      <div class="collapsible-header"><i class="material-icons">add</i>Create New Category</div>
      <div class="collapsible-body">
        <%= form_with model: @category do |f| %>
          <%= f.text_field :name, placeholder: 'category name' %>
          <%= f.submit "Create", class: "btn" %>
          <%= hidden_field_tag :tweet_id, @tweet.id %>
        <% end %>
      </div>
    </li>
  </ul>
  <div class="collection">
    <% @categories.each do |category| %>
      <%= link_to category.name, tweet_path(params: {category_id: category.id}),
                  method: :patch, remote: true, class: 'collection-item' %>
    <% end %>
  </div>
</div>

app/views/tweets/_index.html.erb
<% @tweets.each do |tweet| %>
  <div class="tweet">
    <%= image_tag(tweet.post_user.profile_image, size: 50) %>
    <span class="user"><%= tweet.post_user.name %>
      <span class="screen-name">@<%= tweet.post_user.screen_name %></span></span>
    <span class="content">
          <p><%= text_url_to_link(h(tweet.text)).html_safe %></p>
      <% if tweet.tweet_videos.present? %>
          <%= link_to image_tag(tweet.tweet_videos.first.thumbnail, size: 50),
                      tweet.tweet_videos.first.tweet_video_url, class: 'popup-movie inlink' %>
        <% elsif (tweet.tweet_images.present?) %>
          <div class="popup-image">
          <% tweet.tweet_images.each do |image| %>
            <%= link_to image_tag(image.tweet_image_url, size: 50),
                        image.tweet_image_url, class: 'inlink' %>
          <% end %>
          </div>
        <% end %>
        </span>
    <span class="status">
        <span class="posted-at"><%= tweet.post_created_at.strftime("%Y-%m-%d") %></span>
      <%= tweet.favorite_count %> likes
      <% unless controller.controller_path == 'everybodys/tweets' %>
        <div class="edit-tweet">
        <%= link_to toggle_status_path(tweet), remote: true, method: :patch, class: 'btn btn-small btn-floating grey inlink' do %>
            <i class="material-icons" id="tweet-<%= tweet.id %>-clip">
              <% if tweet.status == 'default' %>
                attach_file
              <% else %>
                attachment
              <% end %>
            </i>
          <% end %>
          <%= link_to edit_tweet_path(tweet), remote: true, class: 'btn-small btn-floating inlink' do %>
            <i class="tiny material-icons">add</i>
          <% end %>
        </div>
          <% end %>
      <span id="tweet-<%= tweet.id %>-category">
            <% if tweet.categories %>
              <% tweet.categories.each do |category| %>
                <%= link_to "##{category.name}", tweets_path(params: {category: {id: category.id}}), class: 'inlink' %>
              <% end %>
            <% end %>
          </span>
        </span>
    <%= link_to '', "https://twitter.com/#{tweet.post_user.screen_name}/status/#{tweet.post_id}", 'aria-hidden': true %>
  </div>
<% end %>
<span class="paginate"><%= paginate @tweets %></span>

app/views/tweets/edit.js.erb
$('#category-modal').html("<%= escape_javascript(render 'form') %>")
$('#category-modal').modal('open');

$(document).ready(function(){
    $('.collapsible').collapsible();
});

app/views/tweets/hashtag.html.erb
<div class="collection with-header">
  <div class="collection-header">
    <h4>ハッシュタグ一覧 <span>(小文字で統一表示)</span></h4>
  </div>
  <% @hashtags.each do |key, value| %>
      <%= link_to "#{key}(#{value})", tweets_path(params: {hash_tag: key}), class: 'collection-item' %>
  <% end %>
</div>

app/views/tweets/index.html.erb
<% if controller.controller_path == 'tweets' %>
  <ul class="tabs">
    <li class="tab col"><%= link_to "一覧", tweets_path, remote: true, class: 'waves-effect' %></li>
    <li class="tab col"><%= link_to "引用", tweets_path(params: {quote: 1}), remote: true, class: 'waves-effect' %></li>
    <li class="tab col"><%= link_to "動画", tweets_path(params: {video: 1}), remote: true, class: 'waves-effect' %></li>
    <li class="tab col"><%= link_to "画像", tweets_path(params: {image: 1}), remote: true, class: 'waves-effect' %></li>
    <li class="tab col"><%= link_to "いいね数", tweets_path(params: {sort: 1}), remote: true, class: 'waves-effect' %></li>
    <li class="tab col"><%= link_to "リプライ", tweets_path(params: {reply: 1}), remote: true, class: 'waves-effect' %></li>
    <li class="tab col"><%= link_to "クリップ", tweets_path(params: {clip: 1}), remote: true, class: 'waves-effect' %></li>
  </ul>
<% end %>

<div id="tweets">
  <%= render 'tweets/index' %>
</div>
<div id="category-modal" class="modal"></div>

app/views/tweets/index.js.erb
$('#tweets').infiniteScroll('destroy');
$('#tweets').html("<%= escape_javascript(render 'tweets/index') %>");
$('.modal').modal();
$('#tweets').infiniteScroll({
path: 'nav.pagination a[rel=next]',
    append: '.tweet',
    prefill: true,
    history: false,
    hideNav: '.pagination',
    onInit: function() {
    this.on( 'append', function() {
        $('.popup-image').magnificPopup({
            delegate : 'a',
            type : 'image',
            mainClass : 'mfp-img-mobile',
            gallery : {
                enabled : true, // ギャラリー表示を有効化
                navigateByImgClick : true, // 画像クリックで次画像へ遷移
                preload : [ 0, 1 ] // いっこ前(0)と後(1)を事前読み込み
            },
            image : {
                verticalFit : true // ブラウザ縦幅に合わせる
            }
        });
        $('.popup-movie').magnificPopup({
            type : 'iframe',
            mainClass : 'mfp-img-mobile'
        });
    });
}
});

$('.popup-image').magnificPopup({
    delegate : 'a',
    type : 'image',
    mainClass : 'mfp-img-mobile',
    gallery : {
        enabled : true, // ギャラリー表示を有効化
        navigateByImgClick : true, // 画像クリックで次画像へ遷移
        preload : [ 0, 1 ] // いっこ前(0)と後(1)を事前読み込み
    },
    image : {
        verticalFit : true // ブラウザ縦幅に合わせる
    }
});
$('.popup-movie').magnificPopup({
    type : 'iframe',
    mainClass : 'mfp-img-mobile'
});

app/views/tweets/toggle_status.js.erb
<% if @tweet.status == 'default' %>
  console.log('default');
  $('#tweet-<%= @tweet.id %>-clip').html("attach_file");
<% else %>
  console.log('cliped');
  $('#tweet-<%= @tweet.id %>-clip').html("attachment");
<% end %>

app/views/tweets/update.js.erb
<% if @status == 'success' %>
$('#tweet-<%= @relationship.tweet_id %>-category').append('<%= link_to "##{@category.name}",
  tweets_path(params: {category: {id: @category.id}}), class: 'inlink' %> ')
console.log('success');
<%  elsif @status == 'fail' %>
console.log('fail');
<% end %>
$("#category-modal").modal('close');