config/routes.rb
Rails.application.routes.draw do
  namespace :everybodys do
    resources :tweets, only: %i[index]
    resources :categories, only: %i[index show]
    resources :users, only: %i[index show]
  end
  root 'home#top'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'users/tweet_fetch', to: 'users#tweet_fetch'
  resources :users, only: %i[edit show update destroy]
  resources :tweets, only: %i[index update edit]
  resources :categories, except: [:show]
  resources :post_users, only: %i[index show]
  patch 'tweets/:id/clip', to: 'tweets#toggle_status', as: 'toggle_status'
  patch 'categories/category_publish/:id', to: 'categories#category_publish', as: 'category_publish'
  get 'tweets/hashtag', to: 'tweets#hashtag'
end

app/models/post_user.rb
class PostUser < ApplicationRecord
  belongs_to :user
  has_many :tweets
  validates :user_id, presence: true
  ransack_alias :search_words, :name_or_screen_name_or_profile_description

  def self.exist_post_user?(uid)
    PostUser.find_by(uid: uid)
  end
end

app/controllers/post_users_controller.rb
class PostUsersController < ApplicationController
  before_action :set_post_user, only: [:show, :update]
  before_action :login_required

  # GET /post_users
  # GET /post_users.json
  def index
    @q = current_user.post_users.ransack(Parameter.new(params).post_user_params)
    @post_users = @q.result.sort_by{ |q| -q.tweets.size }# デフォルトでツイートの多い順に表示
    @post_users = Kaminari.paginate_array(@post_users).page(params[:page]).per(30)
  end

  def show
    @tweets = current_user.post_users.find(params[:id]).tweets.page(params[:page]).per(30)
    render template: 'tweets/index'
  end

  # PATCH/PUT /post_users/1
  # PATCH/PUT /post_users/1.json
  def update
    respond_to do |format|
      if @post_user.update(post_user_params)
        format.html {redirect_to @post_user, notice: 'Post user was successfully updated.'}
        format.json {render :show, status: :ok, location: @post_user}
      else
        format.html {render :edit}
        format.json {render json: @post_user.errors, status: :unprocessable_entity}
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post_user
    @post_user = PostUser.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_user_params
    params.fetch(:post_user, {})
  end
end

app/helpers/post_users_helper.rb
module PostUsersHelper
end

app/views/post_users/index.html.erb
<%= search_form_for @q, url: post_users_path do |f| %>
  <%= f.text_field :search_words_cont, placeholder: 'ユーザー検索' %>
  <%= f.submit 'Search', class: 'btn' %>
<% end %>
<div id="tweets">
<% @post_users.each do |post_user| %>
  <div class="tweet post-user">
    <%= image_tag(post_user.profile_image, size: 50) %>
    <span class="user"><%= post_user.name %>
      <span class="screen-name">@<%= post_user.screen_name %></span></span>
    <span class="content">
        <p><%= post_user.profile_description %></p>
        </span>
      <%= link_to '', post_user_path(post_user.id), 'aria-hidden': true %>
  </div>
<% end %>
</div>
<%= paginate @post_users %>