config/routes.rb
Rails.application.routes.draw do
  namespace :everybodys do
    resources :tweets, only: %i[index]
    resources :categories, only: %i[index show]
    resources :users, only: %i[index show]
  end
  root 'home#top'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'users/tweet_fetch', to: 'users#tweet_fetch'
  resources :users, only: %i[edit show update destroy]
  resources :tweets, only: %i[index update edit]
  resources :categories, except: [:show]
  resources :post_users, only: %i[index show]
  patch 'tweets/:id/clip', to: 'tweets#toggle_status', as: 'toggle_status'
  patch 'categories/category_publish/:id', to: 'categories#category_publish', as: 'category_publish'
  get 'tweets/hashtag', to: 'tweets#hashtag'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :relationships, dependent: :destroy
  has_many :tweets, through: :relationships, dependent: :destroy
  belongs_to :user
  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :status, :user_id, presence: true
  enum status: { unpublish: 0, publish: 1 }

  def toggle_status!
    unpublish? ? publish! : unpublish!
  end

  def self.merge_same_category_tweet(category_name)
    same_category = Category.where(name: category_name, status: :publish)
    if same_category.count > 1
      tweets = same_category.inject do |category, n|
        category.tweets.or(n.tweets)
      end
    elsif
      tweets = same_category.first.tweets
    end
    tweets
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update destroy category_publish]
  before_action :login_required

  def index
    @categories = current_user.categories
    @category = Category.new
  end

  def edit; end


  def create
    @category = current_user.categories.new(category_params)

    # Ajaxの時に使う
    @tweet = Tweet.find(params[:tweet_id]) if params[:tweet_id]

    respond_to do |format|
      if @category.save
        format.html { redirect_to request.referer }
        format.js { @status = 'success'}
      else
        format.html { redirect_to request.referer, notice: 'error'}
        format.js { @status = 'fail'}
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to request.referer, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
        format.js { @status = 'success' }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
        format.js { @status = 'fail' }
      end
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url
  end

  def category_publish
    @category.toggle_status!
    render body: nil
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/everybodys/categories_controller.rb
class Everybodys::CategoriesController < Everybodys::Base
  before_action :set_category, only: [:show]

  def index
    @categories = Category.where(status: :publish).group(:name).having('count(*) >= 1')
  end

  def show
    # 任意のカテゴリーに紐づけられたツイート一覧を表示する
    # 別のユーザが同じ名前のカテゴリー名を作成している場合、同じ名前でツイートをまとめる
    if params[:user].present?
      tweets = User.find(params[:user]).categories.find(params[:id]).tweets
    else
      tweets = Category.merge_same_category_tweet(@category.name)
    end

    @tweets = tweets.page(params[:page]).per(30)
    render template: 'everybodys/tweets/index'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_edit.html.erb
<div class="modal-content">
  <h4>Edit CategoryName</h4>
  <%= form_with model: @category do |f| %>
    <%= f.text_field :name, placeholder: @category.name %>
    <%= f.submit "Edit", class: 'btn-small' %>
  <% end %>
</div>

app/views/categories/create.js.erb
<% if @status == 'success' %>
$('.collection').append('<%= link_to @category.name, tweet_path(id: @tweet.id,category_id: @category.id),
                  method: :patch, remote: true, class: 'collection-item' %>')
<% else %>
console.log('failed');
<% end %>
$('.collapsible').collapsible('close');

app/views/categories/edit.js.erb
$('#edit-category').html("<%= escape_javascript(render 'edit') %>")
$('#edit-category').modal('open');

app/views/categories/index.html.erb
<h3>Category List</h3>
<%= form_for(@category) do |f| %>
  <%= f.label :"NewCategory" %>
  <%= f.text_field :name, placeholder: "Category Name", style: "width: 50%" %>
  <%= f.submit "Add", class: 'btn-small' %>
<% end %>

<% if @categories %>
  <table class="striped">
    <thead>
    <tr>
      <th>カテゴリー名</th>
      <th>ツイート数</th>
      <th>公開設定</th>
    </tr>
    </thead>

    <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td id="category-<%= category.id %>-name"><%= category.name %></td>
        <td><%= category.tweets.length %></td>
        <td>
          <div class="switch">
            <label>
              <%= check_box_tag 'status', category.status, checked = category.publish?, {
                  data: {
                      url: category_publish_path(category),
                      method: :patch,
                      remote: true
                  }
              } %>
              <span class="lever"></span>
            </label>
          </div>
        </td>
        <td>
          <%= link_to edit_category_path(category), remote: true, class: 'btn btn-floating btn-small' do %>
            <i class="material-icons">edit</i>
          <% end %>
        </td>
        <td>
          <%= link_to(category_path(category.id), class: "btn red btn-floating btn-small", method: :delete) do %>
            <i class="material-icons">delete</i>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
<div id="edit-category" class="modal"></div>

app/views/categories/update.js.erb
<% if @status == 'success' %>
$('#category-<%= @category.id %>-name').html('<%= @category.name %>')
<%  elsif @status == 'fail' %>
console.log('fail');
<% end %>
$("#edit-category").modal('close');